module.exports = {
  rules: {
    'vue/attribute-hyphenation': ['warn', 'never', {}],
    'vue/no-v-html': 'off',
    'vue/html-self-closing': ['error', {
      html: {
        void: 'always',
        normal: 'never',
        component: 'always',
      },
      svg: 'any',
    }],
    'vue/html-closing-bracket-spacing': ['warn', {
      selfClosingTag: 'never',
    }],
    'vue/singleline-html-element-content-newline': ['off', {}],
    'vue/max-attributes-per-line': ['error', {
      singleline: 2,
      multiline: 1,
    }],
    'vue/first-attribute-linebreak': ['error', {
      singleline: 'ignore',
      multiline: 'below',
    }],
    'vue/html-closing-bracket-newline': ['error', {
      singleline: 'never',
      multiline: 'always',
    }],
    'vue/script-indent': ['warn', 2, {
      baseIndent: 1,
      switchCase: 1,
      ignores: [],
    }],
    'vue/order-in-components': ['off', {
      order: [
        'el',
        'name',
        'key',
        'parent',
        'functional',
        ['delimiters', 'comments'],
        ['components', 'directives', 'filters'],
        'extends',
        'mixins',
        ['provide', 'inject'],
        'ROUTER_GUARDS',
        'layout',
        'middleware',
        'validate',
        'scrollToTop',
        'transition',
        'loading',
        'inheritAttrs',
        'model',
        ['props', 'propsData'],
        'emits',
        'setup',
        'asyncData',
        'data',
        'fetch',
        'head',
        'computed',
        'watch',
        'watchQuery',
        'LIFECYCLE_HOOKS',
        'methods',
        ['template', 'render'],
        'renderError',
      ],
    }],
    'vue/v-on-event-hyphenation': 'off',
    'vue/multi-word-component-names': 'off',
  },
};
